ALTER TABLE experiences ADD COLUMN visits INTEGER NOT NULL DEFAULT 0;
ALTER TABLE experiences ADD COLUMN up_votes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE experiences ADD COLUMN down_votes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE experiences ADD COLUMN roblox_created DATETIME;
ALTER TABLE experiences ADD COLUMN roblox_updated DATETIME;
