version: "3"
output: prefixed

tasks:
  templ:
    internal: true
    cmds:
      - templ generate --watch --proxy="http://localhost:8003" --cmd="go run ./cmd/web" --open-browser=false

  tailwind:
    internal: true
    cmds:
      - |
        TEMPLUI_PATH="$(go list -mod=mod -m -f '{{.Dir}}' github.com/templui/templui)" && \
        printf '%s\n' \
          '@source "./**/*.templ";' \
          "@source \"$TEMPLUI_PATH/components/**/*.templ\";" \
          > ./assets/css/sources.generated.css && \
        tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch

  cloudflared:
    internal: true
    cmds:
      - cloudflared tunnel run datablox

  web:
    desc: Full except bot (web HMR + tailwind -> http://localhost:8004)
    deps: [tailwind, templ]

  bot:
    desc: Full non HMR (bot stable - no flood/ban)
    cmds:
      - go run ./cmd/bot

  dev:
    desc: Full HMR on (web HMR + bot stable + tunnel - HMR only for web)
    deps: [web, bot, cloudflared]

  prod:
    desc: Production build (templ + tailwind minify + binary)
    cmds:
      - templ generate
      - |
        TEMPLUI_PATH="$(go list -mod=mod -m -f '{{.Dir}}' github.com/templui/templui)" && \
        printf '%s\n' \
          '@source "./**/*.templ";' \
          "@source \"$TEMPLUI_PATH/components/**/*.templ\";" \
          > ./assets/css/sources.generated.css && \
        tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --minify
      - go build -o ./bin/bot.exe ./cmd/bot
      - go build -o ./bin/web.exe ./cmd/web
